# Generated by Django 2.2.5 on 2020-01-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset_vuejs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
