# Generated by Django 2.2.5 on 2020-01-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset_vuejs', '0002_delete_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
